<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFramework>net48</TargetFramework>
		<OutputType>Exe</OutputType>
		<Platforms>AnyCPU;x64;x86</Platforms>
		<UseWPF>true</UseWPF>
		<UseWindowsForms>true</UseWindowsForms>
		<IsPackable>false</IsPackable>
	</PropertyGroup>

	<ItemGroup>
		<PackageReference Include="xunit.v3" Version="3.2.2" />
		<PackageReference Include="xunit.runner.visualstudio" Version="3.1.5" />
		<PackageReference Include="Microsoft.NET.Test.Sdk" Version="18.8.1" />
		<PackageReference Include="Xunit.StaFact" Version="3.0.13" />
	</ItemGroup>

	<ItemGroup>
		<ProjectReference Include="..\SylphyHorn\SylphyHorn.csproj">
			<AdditionalProperties>RunSylphyHornPostBuild=false</AdditionalProperties>
		</ProjectReference>
		<Reference Include="MetroTrilithon">
			<HintPath>..\libraries\MetroTrilithon.Desktop\$(TargetFramework)\MetroTrilithon.dll</HintPath>
		</Reference>
	</ItemGroup>

</Project>
