<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFrameworks>net48;net10.0-windows10.0.26100.0</TargetFrameworks>
    <SupportedOSPlatformVersion>10.0.17763.0</SupportedOSPlatformVersion>
    <RootNamespace>SylphyHorn</RootNamespace>
    <AssemblyName>SchedulerManager</AssemblyName>
    <Platforms>AnyCPU;x64;x86</Platforms>
    <RuntimeIdentifiers>win-x86;win-x64;win-arm64</RuntimeIdentifiers>
  </PropertyGroup>

  <PropertyGroup>
    <AppendRuntimeIdentifierToOutputPath>false</AppendRuntimeIdentifierToOutputPath>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Release|AnyCPU'">
    <PlatformTarget>AnyCPU</PlatformTarget>
    <OutputPath Condition="'$(UseArtifactsOutput)' != 'true'">..\SylphyHorn\bin\$(Configuration)\</OutputPath>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Release|x64'">
    <PlatformTarget>x64</PlatformTarget>
    <OutputPath Condition="'$(UseArtifactsOutput)' != 'true'">..\SylphyHorn\bin\$(Platform)\$(Configuration)\</OutputPath>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Release|x86'">
    <PlatformTarget>x86</PlatformTarget>
    <OutputPath Condition="'$(UseArtifactsOutput)' != 'true'">..\SylphyHorn\bin\$(Platform)\$(Configuration)\</OutputPath>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Debug|AnyCPU'">
    <PlatformTarget>AnyCPU</PlatformTarget>
    <OutputPath Condition="'$(UseArtifactsOutput)' != 'true'">..\SylphyHorn\bin\$(Configuration)\</OutputPath>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Debug|x64'">
    <PlatformTarget>x64</PlatformTarget>
    <OutputPath Condition="'$(UseArtifactsOutput)' != 'true'">..\SylphyHorn\bin\$(Platform)\$(Configuration)\</OutputPath>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Debug|x86'">
    <PlatformTarget>x86</PlatformTarget>
    <OutputPath Condition="'$(UseArtifactsOutput)' != 'true'">..\SylphyHorn\bin\$(Platform)\$(Configuration)\</OutputPath>
  </PropertyGroup>

  <ItemGroup Condition="'$(TargetFramework)' == 'net10.0-windows10.0.26100.0'">
    <FrameworkReference Include="Microsoft.WindowsDesktop.App" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="TaskScheduler" Version="2.12.2" />
  </ItemGroup>

</Project>
